name: BusineWealthJS1
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3779259920120239
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeff5'
    - '#08090b'
    - '#9e9ea6'
    - '#4d5e6e'
    - '#ddbd6a'
  brandStrength: 0.8630383210256696
  lightness: 0.6630403930321336
  saturation: 0.8515455713495612
  rhythmicContrast: 0.3040507168043405
purpose: []
